import type { Metadata } from 'next';
import { Nunito_Sans } from 'next/font/google';
import './globals.css';
import HeaderHomePage from '@/components/Header-home-page';
import FooterHomePage from '@/components/Footer-home-page';

const nunitoSans = Nunito_Sans({
  variable: '--font-nunito-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Subtrack',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='fr'>
      <body
        className={`${nunitoSans.className}  antialiased bg-homepage-blue min-h-screen flex flex-col `}
      >
        <HeaderHomePage />

        <main className=' text-colorone flex-grow '>{children}</main>
        <FooterHomePage />
      </body>
    </html>
  );
}
