import type { Metadata } from 'next';
import { Nunito_Sans } from 'next/font/google';
import './globals.css';
import HeaderHomePage from '@/src/components/Header-home-page';
import FooterHomePage from '@/src/components/Footer-home-page';
import { SessionProvider } from 'next-auth/react';

const nunitoSans = Nunito_Sans({
  variable: '--font-nunito-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Subtrack',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.png',
    apple: '/logo.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang='fr'>
        <body
          className={`${nunitoSans.className}  antialiased bg-homepage-blue min-h-screen flex flex-col `}
        >
          <HeaderHomePage />

          <main className=' text-blue flex-grow '>{children}</main>
          <FooterHomePage />
        </body>
      </html>
    </SessionProvider>
  );
}
