import type { Metadata } from 'next';
import { Nunito_Sans } from 'next/font/google';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import QueryProvider from './providers/Query-provider';
import { Toast, ToastProvider } from './providers/Toast-provider';

const nunitoSans = Nunito_Sans({
  variable: '--font-nunito-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Subtrack',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.png',
    apple: '/logo.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <ToastProvider>
        <QueryProvider>
          <html lang='fr'>
            <body className={`${nunitoSans.className} antialiased `}>
              <main>
                {children}
                <Toast />
              </main>
            </body>
          </html>
        </QueryProvider>
      </ToastProvider>
    </SessionProvider>
  );
}
